version: "3.8"
services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgresql_master_data:/bitnami/postgresql
      - ./replication-user-grant.sql:/docker-entrypoint-initdb. d/db.sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master              # 복제 모드 [master / slave]
      - POSTGRESQL_REPLICATION_USER=repl_user           # 복제 사용자 이름
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password   # 복제 사용자 비밀번호
      - POSTGRESQL_USERNAME=taesu
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=demo

  postgesql-read1:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433:5432'
    restart: on-failure
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave               # 복제 모드 [master / slave]
      - POSTGRESQL_REPLICATION_USER=repl_user           # 복제 사용자 이름
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password   # 복제 사용자 비밀번호
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=taesu
      - POSTGRESQL_PASSWORD=password

volumes:
  postgresql_master_data:
    driver: local
