spring:
  config:
    import: "classpath:/postgres_datasource.yml"
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:postgresql://localhost:5432/demo?reWriteBatchedInserts=true
        max-lifetime: 1800000 # (ms), default
        connection-timeout: 10000
        validation-timeout: 10000
        driver-class-name: org.postgresql.Driver
        username: taesu
        password: password
        maximum-pool-size: 10
        pool-name: master-cp
      replica1:
        jdbc-url: jdbc:postgresql://localhost:5433/demo?reWriteBatchedInserts=true
        max-lifetime: 1800000 # (ms), default
        connection-timeout: 10000
        validation-timeout: 10000
        driver-class-name: org.postgresql.Driver
        username: taesu
        password: password
        maximum-pool-size: 10
        pool-name: replica1-cp

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
logging:
  level:
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
