spring:
  datasource:
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.default_batch_fetch_size: 1000
      hibernate.dialect.storage_engine: innodb
      hibernate.jdbc.fetch_size: ${spring.jdbc.template.fetch-size}
      hibernate.create_empty_composites.enabled: true
